site_name: ConsenSys Academy Bootcamp
repo_url: https://github.com/kevinbluer/Blockchain-Developer-Bootcamp
edit_uri: edit/main/docs/
theme:
  name: null
  custom_dir: 'custom_theme/'
google_analytics:
  - UA-262533-24
  - auto
markdown_extensions:
  - attr_list